#!/usr/bin/php
<?php declare(strict_types=1);

$libraryUrl = 'https://metacpan.org/dist/Text-Unidecode';
$expectedVersion = '1.30';

$sourceGzip = file_get_contents(
	$libraryUrl,
	FALSE,
	stream_context_create([
		'http' => [
			'method' => 'GET',
			'header' => "Accept-Encoding: gzip\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36\r\n"
		]
	])
);

if ($sourceGzip === FALSE) {
	echo sprintf('Can\'t download page "%s".', $libraryUrl) . PHP_EOL;
	exit(1);
}

$source = gzdecode($sourceGzip);

if ($source === FALSE) {
	echo sprintf('Can\'t gzdecode "%s".', $libraryUrl) . PHP_EOL;
	exit(1);
}

if (preg_match('#<span class="release-name">Text-Unidecode-(?<version>[0-9\.]+)</span>#', $source, $matches) !== 1) {
	echo sprintf('Can\'t get current version from page "%s".', $libraryUrl) . PHP_EOL;
	exit(1);
}

$success = $expectedVersion === $matches['version'];

echo sprintf('[%s] => Actual version \'%s\' %s Expected \'%s\'', $success ? 'OK' : 'FAIL', $matches['version'], $success ? '==' : '!=', $expectedVersion). PHP_EOL;

exit($success ? 0 : 1);
